# Generated by Django 5.1 on 2024-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=12)),
                ('desc', models.TextField(blank=True, null=True)),
                ('namecompany', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
